name: Run Jest Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run Jest tests
      run: npm test

    - name: Archive Jest test results
      uses: actions/upload-artifact@v2
      with:
        name: jest-test-results
        path: path/to/your/test-results-directory
        retention-days: 30
